#ls
echo "diff ls - ft_ls : "
diff sorties/sortiels sorties/sortieft
diff sorties/sortie_ls sorties/sortie_ft
diff sorties/sortie_ls_point sorties/sortie_ft_point
diff sorties/sortie_ls_slash sorties/sortie_ft_slash
diff sorties/sortie_ls_tild sorties/sortie_ft_tild
diff sorties/sortie_ls_multi sorties/sortie_ft_multi
diff sorties/sortie_ls_nonex sorties/sortie_ft_nonex
diff sorties/sortie_ls_direc sorties/sortie_ft_direc
diff sorties/sortie_ls_files sorties/sortie_ft_files
diff sorties/sortie_ls_dev sorties/sortie_ft_dev
diff sorties/sortie_ls_bin sorties/sortie_ft_bin
diff sorties/sortie_ls_users sorties/sortie_ft_users

#ls -a
echo "\ndiff ls -a - ft_ls -a :"
diff sorties/sortie_ls_all sorties/sortie_ft_all
diff sorties/sortie_ls_allpoint sorties/sortie_ft_allpoint
diff sorties/sortie_ls_allslash sorties/sortie_ft_allslash
diff sorties/sortie_ls_alltild sorties/sortie_ft_alltild
diff sorties/sortie_ls_allmulti sorties/sortie_ft_allmulti
diff sorties/sortie_ls_allnonex sorties/sortie_ft_allnonex
diff sorties/sortie_ls_alldirec sorties/sortie_ft_alldirec
diff sorties/sortie_ls_allfiles sorties/sortie_ft_allfiles
diff sorties/sortie_ls_alldev sorties/sortie_ft_alldev
diff sorties/sortie_ls_allbin sorties/sortie_ft_allbin
diff sorties/sortie_ls_allusers sorties/sortie_ft_allusers

#ls -t
echo "\ndiff ls -t - ft_ls -t :"
diff sorties/sortie_ls_time sorties/sortie_ft_time
diff sorties/sortie_ls_timepoint sorties/sortie_ft_timepoint
diff sorties/sortie_ls_timeslash sorties/sortie_ft_timeslash
diff sorties/sortie_ls_timetild sorties/sortie_ft_timetild
diff sorties/sortie_ls_timemulti sorties/sortie_ft_timemulti
diff sorties/sortie_ls_timenonex sorties/sortie_ft_timenonex
diff sorties/sortie_ls_timedirec sorties/sortie_ft_timedirec
diff sorties/sortie_ls_timefiles sorties/sortie_ft_timefiles
#diff sorties/sortie_ls_timedev sorties/sortie_ft_timedev
diff sorties/sortie_ls_timebin sorties/sortie_ft_timebin
diff sorties/sortie_ls_timeusers sorties/sortie_ft_timeusers

#ls -r
echo "\ndiff ls -r - ft_ls -r :"
diff sorties/sortie_ls_reverse sorties/sortie_ft_reverse
diff sorties/sortie_ls_reversepoint sorties/sortie_ft_reversepoint
diff sorties/sortie_ls_reverseslash sorties/sortie_ft_reverseslash
diff sorties/sortie_ls_reversetild sorties/sortie_ft_reversetild
diff sorties/sortie_ls_reversemulti sorties/sortie_ft_reversemulti
diff sorties/sortie_ls_reversenonex sorties/sortie_ft_reversenonex
diff sorties/sortie_ls_reversedirec sorties/sortie_ft_reversedirec
diff sorties/sortie_ls_reversefiles sorties/sortie_ft_reversefiles
diff sorties/sortie_ls_reversedev sorties/sortie_ft_reversedev
diff sorties/sortie_ls_reversebin sorties/sortie_ft_reversebin
diff sorties/sortie_ls_reverseusers sorties/sortie_ft_reverseusers

#ls -at
echo "\ndiff ls -at - ft_ls -at :"
diff sorties/sortie_ls_alltime sorties/sortie_ft_alltime
diff sorties/sortie_ls_alltimepoint sorties/sortie_ft_alltimepoint
diff sorties/sortie_ls_alltimeslash sorties/sortie_ft_alltimeslash
diff sorties/sortie_ls_alltimetild sorties/sortie_ft_alltimetild
diff sorties/sortie_ls_alltimemulti sorties/sortie_ft_alltimemulti
diff sorties/sortie_ls_alltimenonex sorties/sortie_ft_alltimenonex
diff sorties/sortie_ls_alltimedirec sorties/sortie_ft_alltimedirec
diff sorties/sortie_ls_alltimefiles sorties/sortie_ft_alltimefiles
#diff sorties/sortie_ls_alltimedev sorties/sortie_ft_alltimedev
diff sorties/sortie_ls_alltimebin sorties/sortie_ft_alltimebin
diff sorties/sortie_ls_alltimeusers sorties/sortie_ft_alltimeusers

#ls -ar
echo "\ndiff ls -ar - ft_ls -ar :"
diff sorties/sortie_ls_allreverse sorties/sortie_ft_allreverse
diff sorties/sortie_ls_allreversepoint sorties/sortie_ft_allreversepoint
diff sorties/sortie_ls_allreverseslash sorties/sortie_ft_allreverseslash
diff sorties/sortie_ls_allreversetild sorties/sortie_ft_allreversetild
diff sorties/sortie_ls_allreversemulti sorties/sortie_ft_allreversemulti
diff sorties/sortie_ls_allreversenonex sorties/sortie_ft_allreversenonex
diff sorties/sortie_ls_allreversedirec sorties/sortie_ft_allreversedirec
diff sorties/sortie_ls_allreversefiles sorties/sortie_ft_allreversefiles
diff sorties/sortie_ls_allreversedev sorties/sortie_ft_allreversedev
diff sorties/sortie_ls_allreversebin sorties/sortie_ft_allreversebin
diff sorties/sortie_ls_allreverseusers sorties/sortie_ft_allreverseusers

#ls -tr
echo "\ndiff ls -tr - ft_ls -tr :"
diff sorties/sortie_ls_timereverse sorties/sortie_ft_timereverse
diff sorties/sortie_ls_timereversepoint sorties/sortie_ft_timereversepoint
diff sorties/sortie_ls_timereverseslash sorties/sortie_ft_timereverseslash
diff sorties/sortie_ls_timereversetild sorties/sortie_ft_timereversetild
diff sorties/sortie_ls_timereversemulti sorties/sortie_ft_timereversemulti
diff sorties/sortie_ls_timereversenonex sorties/sortie_ft_timereversenonex
diff sorties/sortie_ls_timereversedirec sorties/sortie_ft_timereversedirec
diff sorties/sortie_ls_timereversefiles sorties/sortie_ft_timereversefiles
#diff sorties/sortie_ls_timereversedev sorties/sortie_ft_timereversedev
diff sorties/sortie_ls_timereversebin sorties/sortie_ft_timereversebin
diff sorties/sortie_ls_timereverseusers sorties/sortie_ft_timereverseusers

#ls -atr
echo "\ndiff ls -atr - ft_ls -atr :"
diff sorties/sortie_ls_alltimereverse sorties/sortie_ft_alltimereverse
diff sorties/sortie_ls_alltimereversepoint sorties/sortie_ft_alltimereversepoint
diff sorties/sortie_ls_alltimereverseslash sorties/sortie_ft_alltimereverseslash
diff sorties/sortie_ls_alltimereversetild sorties/sortie_ft_alltimereversetild
diff sorties/sortie_ls_alltimereversemulti sorties/sortie_ft_alltimereversemulti
diff sorties/sortie_ls_alltimereversenonex sorties/sortie_ft_alltimereversenonex
diff sorties/sortie_ls_alltimereversedirec sorties/sortie_ft_alltimereversedirec
diff sorties/sortie_ls_alltimereversefiles sorties/sortie_ft_alltimereversefiles
#diff sorties/sortie_ls_alltimereversedev sorties/sortie_ft_alltimereversedev
diff sorties/sortie_ls_alltimereversebin sorties/sortie_ft_alltimereversebin
diff sorties/sortie_ls_alltimereverseusers sorties/sortie_ft_alltimereverseusers

#ls -R
echo "\ndiff ls -R - ft_ls -R : "
diff sorties/sortie_ls_recur sorties/sortie_ft_recur
diff sorties/sortie_ls_recurpoint sorties/sortie_ft_recurpoint
diff sorties/sortie_ls_recurslash sorties/sortie_ft_recurslash
diff sorties/sortie_ls_recurtild sorties/sortie_ft_recurtild
diff sorties/sortie_ls_recurmulti sorties/sortie_ft_recurmulti
diff sorties/sortie_ls_recurnonex sorties/sortie_ft_recurnonex
diff sorties/sortie_ls_recurdirec sorties/sortie_ft_recurdirec
diff sorties/sortie_ls_recurfiles sorties/sortie_ft_recurfiles
#diff sorties/sortie_ls_recurdev sorties/sortie_ft_recurdev
diff sorties/sortie_ls_recurbin sorties/sortie_ft_recurbin
diff sorties/sortie_ls_recurusers sorties/sortie_ft_recurusers
